apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  selector:
    app: goserver
  # type: NodePort
  type: LoadBalancer #exporta porta utilizado para provedores de serviços para publicar serviços
  # type: ClusterIP
  ports:
  - name: goserver-service
    port: 80 # Porta do serviço
    targetPort: 80 # Porta do container
    protocol: TCP
    

# Libera a porta de todos os nós
# Node 1 : 30000 > < 32767 --------> 30001
# Node 2 : 30001
# Node 3 : 30001
# Node 4 : 30001